# Generated by Django 3.2.20 on 2023-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brith_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
