# Generated by Django 3.2.20 on 2023-11-20 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_brith_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car_images',
        ),
        migrations.AddField(
            model_name='images',
            name='type_img',
            field=models.SmallIntegerField(choices=[(1, 'CAR'), (2, 'TOTAL')], default=2),
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_thumb', to=settings.AUTH_USER_MODEL),
        ),
    ]
